# Generated by Django 3.2.13 on 2022-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='running_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
